version: '3'

services:
  python_app:
    build: .
    container_name: python_app
    platform: linux/amd64
    volumes:
      - ./code:/app/code
      - ./data:/app/data
    working_dir: /app
    stdin_open: true
    tty: true